class auth_error(Exception):
    pass